#!/bin/bash




#network model
net_model=Linear

#network dimensions
m_dim=576
m_prime=8






batch=8


for data in MTR_rf2_dc1.5_outliers00 #MTR_rf2_dc1.5_outliers01 MTR_rf2_dc1.5_outliers02 MTR_rf2_dc1.5_outliers03
do
    for p in  1 2 1.5
    do
        for lr in 0.00001 
        do
             for momentum in 0.9
             do
                 sbatch -p short  --mem 100g  --constraint E5-2680v4@2.40GHz  --job-name MBO2$data  MBOSGD_script $data   $net_model $m_dim $m_prime $batch $p $lr $momentum
             done
        done
    done
done




