#!/bin/bash




#network model
net_model=LinearSoft

#network dimensions
m_dim=280
m_prime=16





batch=8


for data in MTR_scm1d_dc5_outliers005  MTR_scm1d_dc5_outliers01 MTR_scm1d_dc5_outliers02 MTR_scm1d_dc5_outliers03
#MNIST_dc1.5__Fakeoutliers00 MNIST_dc1.5__Fakeoutliers005 MNIST_dc1.5__Fakeoutliers01 MNIST_dc1.5__Fakeoutliers02 MNIST_dc1.5__Fakeoutliers03 FashionMNIST_dc1.5__Fakeoutliers00 FashionMNIST_dc1.5__Fakeoutliers005 FashionMNIST_dc1.5__Fakeoutliers01 FashionMNIST_dc1.5__Fakeoutliers02 FashionMNIST_dc1.5__Fakeoutliers03
do
    for p in  1 2 1.5
    do
        for lr in  0.001 #0.001 
        do
             for momentum in 0.9
             do
                 sbatch -p ioannidis  --mem 130g  --job-name MBO2$data  MBOSGD_script $data   $net_model $m_dim $m_prime $batch $p $lr $momentum
             done
        done
    done
done




