#!/bin/bash




#network model
net_model=ConvAEC2Soft

#network dimensions
m_dim=1
m_prime=8





batch=8

for data in FashionMNIST_dc1.5__Fakeoutliers00 FashionMNIST_dc1.5__Fakeoutliers005 FashionMNIST_dc1.5__Fakeoutliers01 FashionMNIST_dc1.5__Fakeoutliers02 FashionMNIST_dc1.5__Fakeoutliers03
do
    for p in   1 1.5 2 -2
    do
        for lr in  0.000001
        do
            for momentum in 0.9 
            do
                sbatch  -p ioannidis  --mem 100g --job-name SGD$data  --constraint E5-2680v4@2.40GHz  MBO_script $data SGD  $net_model $m_dim $m_prime $batch $p $lr $momentum
            done
        done
    done

done




