#!/bin/bash




#network model
net_model=ConvAEC2

#network dimensions
m_dim=1
m_prime=16




job_name=$net_model

lr=0.001
momentum=0.0


batch=8

#dataset
for data in MNIST_CIFAR10outliers00 MNIST_CIFAR10outliers005 MNIST_CIFAR10outliers01
do

    for p in 1 1.5 2
    do
         sbatch -p ioannidis --mem 100g  --job-name $job_name MBO_script $data MBO  $net_model $m_dim $m_prime $batch $p $lr $momentum
    done
done




