#!/bin/bash




#network model
net_model=ConvAEC2Soft

#network dimensions
m_dim=1
m_prime=8






batch=8


for data in MNIST_dc1.5_outliers00
do
    for p in  1 #2 1.5
    do
        for lr in 0.00001 
        do
             for momentum in 0.9
             do
                 ./dgx_MBOSGD_spt $data   $net_model $m_dim $m_prime $batch $p $lr $momentum
             done
        done
    done
done




