#!/bin/bash




#network model
net_model=LinearSoft

#network dimensions
m_dim=280
m_prime=16





lr=0.001
momentum=0.0


batch=8

#dataset
for data in  MTR_scm1d_dc5_outliers005 MTR_scm1d_dc5_outliers01 MTR_scm1d_dc5_outliers02 MTR_scm1d_dc5_outliers03  
do

    for p in  1 1.5 2
    do
         sbatch  --partitio ioannidis   --mem 130g   --job-name $data  MBO_script $data MBO  $net_model $m_dim $m_prime $batch $p $lr $momentum
    done
done




