#!/bin/bash




#network model
net_model=LinearSoft

#network dimensions
m_dim=280
m_prime=16





batch=8

for data in MTR_scm1d_dc5_outliers005 MTR_scm1d_dc5_outliers01 MTR_scm1d_dc5_outliers02 MTR_scm1d_dc5_outliers03
do
    for p in   1 1.5 2 -2
    do
        for lr in 0.000001
        do
            for momentum in  0.9 
            do
                sbatch  -p ioannidis  --mem 130g --job-name SGD$data    MBO_script $data SGD  $net_model $m_dim $m_prime $batch $p $lr $momentum
            done
        done
    done

done




